### ISSUE TITLE
charmap decoding error

### ISSUE THREAD

**Issue by ElricPi** [PAHdb/pyPAHdb#37] opened 2021-09-23 08:46 UTC
![image](https://user-images.githubusercontent.com/72200932/134476956-23a70f04-7c76-4f0d-aba0-b1d68a99fa6b.png)
![image](https://user-images.githubusercontent.com/72200932/134477252-6e690372-4db7-48c5-a1ec-8273985f4d9a.png)

Hello,

I faced another error while running this code to get the observation for the .fits file as well as the .tbl file. I have attached the screenshot - can you kindly look into it? I'll be grateful once more. I have also attached screenshot for the modules which i entered. The data was taken from the following archive: https://sha.ipac.caltech.edu/applications/Spitzer/SHA/#id=SearchByPosition&RequestClass=ServerRequest&DoSearch=true&SearchByPosition.field.radius=0.13888889000000001&UserTargetWorldPt=11.888;-25.28822;EQ_J2000&TargetPanel.field.targetName=ngc%20253&SimpleTargetPanel.field.resolvedBy=nedthensimbad&MoreOptions.field.prodtype=pbcd&shortDesc=Position&isBookmarkAble=true&isDrillDownRoot=true&isSearchResult=true

Also, the sample files for this code are running perfectly. Specifically the sample data for ngc 7023. Both the .fits and .tbl files.

Thank You.

**Comment by alexmaragko** [comment] 2021-09-28 10:57
The charmap decoding is a warning and not the actual error. The "Format not recognized" is the problem here, and this is because you are trying to load an IRAC map observation. pyPAHdb however will only handle IRS spectra and spectral cubes.

**Comment by ElricPi** [comment] 2021-10-04 14:02
Hello,
Thank you for pointing the error but unfortunately I'm still not able to work with it and I think I'm having some trouble in understanding the kind of data I need to select. I would be grateful if you could kindly point me towards a Spitzer data which would avoid the error. Also I would really appreciate it if the data could be provided within the following bandpass: 5.2 - 14.5 microns. 

Thank you once more. 


Edit: Specifically I'm interested in the following objects:
NGC 7027, NGC 7023, HD 97048, HD 44179, IRAS 02575+6017, NGC 253.

**Comment by PAHdb** [comment] 2021-10-04 18:18
pyPAHdb works on infrared _spectra_. You provided pyPAHdb with an IRAC _image_. Spitzer spectra can be directly obtained from the [SHA](https://sha.ipac.caltech.edu/applications/Spitzer/SHA/) and/or, for example, [CASSIS](https://cassis.sirtf.com). Note that these data would still require some pre-processing before feeding it to pyPAHdb. For example, you might need to splice the different orders and certainly would want to remove any continuum and emission line components. For a somewhat comprehensive overview for the steps involved you could take a look at [Boersma+ (2018)](http://dx.doi.org/10.3847/1538-4357/aabcbe).

Unfortunately, we are not in a position to provide you with the pre-processed data; this is the researcher's own responsibility. For some of the objects you list no Spitzer data are available. Though, you can perhaps look at the [Sloan ISO SWS Atlas](https://users.physics.unc.edu/~gcsloan/library/swsatlas/aot1.html) for those spectra. Note that a Spitzer spectral cube for NGC 7023 is actual included with pyPAHdb, which is used by example_fits.py. These data are from  [Boersma+ (2018)](http://dx.doi.org/10.3847/1538-4357/aabcbe).

Since pyPAHdb shows expected behavior, I'm closing the issue.

**Closed as completed by PAHdb** 2021-10-04 18:18 UTC
